local oceanum = require('oceanum')
local config = require('oceanum.config')

describe('oceanum module', function()
  it('loads without error', function()
    assert.is_not_nil(oceanum)
  end)

  it('has setup function', function()
    assert.is_function(oceanum.setup)
  end)

  it('has get_config function', function()
    assert.is_function(oceanum.get_config)
  end)
end)

describe('oceanum config', function()
  it('has default values', function()
    local cfg = config.get()
    assert.is_not_nil(cfg)
    assert.is_string(cfg.token_env_var)
    assert.is_string(cfg.ai_backend_url)
    assert.is_string(cfg.datamesh_ui_url)
  end)

  it('merge returns defaults when no user config', function()
    local merged = config.merge(nil)
    assert.is_not_nil(merged)
    assert.equals('OCEANUM_API_KEY', merged.token_env_var)
    assert.equals('https://ai.oceanum.io', merged.ai_backend_url)
    assert.equals('https://ui.datamesh.oceanum.io', merged.datamesh_ui_url)
  end)

  it('merge merges user config with defaults', function()
    local merged = config.merge({ token_env_var = 'MY_TOKEN' })
    assert.equals('MY_TOKEN', merged.token_env_var)
    assert.equals('https://ai.oceanum.io', merged.ai_backend_url)
  end)
end)
